In [1]:
import pandas as pd
import numpy as np
from tools import get_project_path

In [2]:
SDPu_tab= pd.read_csv(get_project_path("results/benchmark/6x100-0.026/01_25_23h23_48s_run-SDPu-FP-RLT=100/results.csv"))
BB_tab = pd.read_csv(get_project_path("results/benchmark/mnist-6x100_0.026/2026-01-29_14-42-11_BB-alpha-beta-CROWN_test-bb/summary.csv"))
BB_tab["data_index"] = SDPu_tab["data_index"]

list_of_tab = {
    "SDPu" : SDPu_tab,
    "BB" : BB_tab,
}

In [3]:
for name, tab in list_of_tab.items():
    print(f"Processing table: {name}, number of columns : {len(tab.columns)}, number of rows : {len(tab)}")

Processing table: SDPu, number of columns : 31, number of rows : 100
Processing table: BB, number of columns : 10, number of rows : 100

In [4]:
def traite_tableau_branch_and_bound(tab, name):

    print("Columns before renaming :", tab.columns)
    tab.rename(columns={col : name + "_" + col for col in tab.columns if col != "data_index"}, errors='raise', inplace=True)
    print("New columns :", tab.columns)

In [5]:
def traite_tableau_sdp(tab, name):
    if "RLT_prop" in tab.columns:
        tab["RLT_prop"] = tab["RLT_prop"].fillna(0)
        RLT_prop = tab["RLT_prop"].unique()
        
        print("RLT_prop:", RLT_prop)
        #RLT_props = [0, 0.1, 0.3, 0.5]
        #tab = tab[tab["RLT_prop"].isin(RLT_props)].copy()

    tab["total_time"] = tab["time"] + tab["bound_time"]
    tab["robust"] = (tab["optimal_value"] >= 0) | (tab["status"]=="trivially_solved")
    tab["target"] = tab["target"].fillna("unknown")

    print("Columns before renaming :", tab.columns)
    tab.rename(columns={col : name+ "_" + col for col in tab.columns if col != "data_index"}, errors='raise', inplace=True)
    print("New columns :", tab.columns)

In [6]:
for name, tab in list_of_tab.items():
    display(tab)
    if "Branch_and_Bound" in name:
        traite_tableau_branch_and_bound(tab, name)
    elif "SDP" in name:
        traite_tableau_sdp(tab, name)
    display(tab)

,LAST_LAYER,MATRIX_BY_LAYERS,McC_betaz_logits,Nb_constraints,Nb_stable_actives,Nb_stable_inactives,RLT,RLT_prop,Tij,Tij_before_penultimate_layer,...,label_predicted,model,network,optimal_value,pretreatment_time,primal_obj_value,status,target,time,triangularization
0,False,True,NaN,NaN,192,301,NaN,NaN,NaN,NaN,...,0,MdSDP,6x100,NaN,0.000000,NaN,trivially_solved,NaN,0.000000,NaN
1,False,True,NaN,NaN,201,306,NaN,NaN,NaN,NaN,...,0,MdSDP,6x100,NaN,0.000000,NaN,trivially_solved,NaN,0.000000,NaN
2,False,True,NaN,NaN,208,298,NaN,NaN,NaN,NaN,...,0,MdSDP,6x100,NaN,0.000000,NaN,trivially_solved,NaN,0.000000,NaN
3,False,True,NaN,NaN,203,293,NaN,NaN,NaN,NaN,...,0,MdSDP,6x100,NaN,0.000000,NaN,trivially_solved,NaN,0.000000,NaN
4,False,True,NaN,NaN,199,305,NaN,NaN,NaN,NaN,...,0,MdSDP,6x100,NaN,0.000000,NaN,trivially_solved,NaN,0.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,False,True,NaN,NaN,196,307,NaN,NaN,NaN,NaN,...,9,MdSDP,6x100,NaN,0.000000,NaN,trivially_solved,NaN,0.000000,NaN
96,False,True,True,84229.0,149,191,True,1.0,True,True,...,3,MdSDP,6x100,-0.865488,251.804380,-0.842235,0,NaN,1102.682588,True
97,False,True,True,33280.0,192,283,True,1.0,True,True,...,4,MdSDP,6x100,-2.299313,164.277891,-2.276060,0,NaN,1037.783418,True
98,False,True,NaN,NaN,197,293,NaN,NaN,NaN,NaN,...,9,MdSDP,6x100,NaN,0.000000,NaN,trivially_solved,NaN,0.000000,NaN
99,False,True,True,29400.0,202,287,True,1.0,True,True,...,0,MdSDP,6x100,-3.819140,153.741740,-3.795887,0,NaN,1005.150132,True

RLT_prop: [0. 1.]
Columns before renaming : Index(['LAST_LAYER', 'MATRIX_BY_LAYERS', 'McC_betaz_logits', 'Nb_constraints',
       'Nb_stable_actives', 'Nb_stable_inactives', 'RLT', 'RLT_prop', 'Tij',
       'Tij_before_penultimate_layer', 'USE_STABLE_ACTIVES',
       'USE_STABLE_INACTIVES', 'beta_logits_comparaison_1',
       'beta_logits_comparaison_2', 'bound_time', 'data_index', 'dataset',
       'dual_obj_value', 'epsilon', 'iterations', 'label', 'label_predicted',
       'model', 'network', 'optimal_value', 'pretreatment_time',
       'primal_obj_value', 'status', 'target', 'time', 'triangularization',
       'total_time', 'robust'],
      dtype='object')
New columns : Index(['SDPu_LAST_LAYER', 'SDPu_MATRIX_BY_LAYERS', 'SDPu_McC_betaz_logits',
       'SDPu_Nb_constraints', 'SDPu_Nb_stable_actives',
       'SDPu_Nb_stable_inactives', 'SDPu_RLT', 'SDPu_RLT_prop', 'SDPu_Tij',
       'SDPu_Tij_before_penultimate_layer', 'SDPu_USE_STABLE_ACTIVES',
       'SDPu_USE_STABLE_INACTIVES', 'SDPu_beta_logits_comparaison_1',
       'SDPu_beta_logits_comparaison_2', 'SDPu_bound_time', 'data_index',
       'SDPu_dataset', 'SDPu_dual_obj_value', 'SDPu_epsilon',
       'SDPu_iterations', 'SDPu_label', 'SDPu_label_predicted', 'SDPu_model',
       'SDPu_network', 'SDPu_optimal_value', 'SDPu_pretreatment_time',
       'SDPu_primal_obj_value', 'SDPu_status', 'SDPu_target', 'SDPu_time',
       'SDPu_triangularization', 'SDPu_total_time', 'SDPu_robust'],
      dtype='object')

,SDPu_LAST_LAYER,SDPu_MATRIX_BY_LAYERS,SDPu_McC_betaz_logits,SDPu_Nb_constraints,SDPu_Nb_stable_actives,SDPu_Nb_stable_inactives,SDPu_RLT,SDPu_RLT_prop,SDPu_Tij,SDPu_Tij_before_penultimate_layer,...,SDPu_network,SDPu_optimal_value,SDPu_pretreatment_time,SDPu_primal_obj_value,SDPu_status,SDPu_target,SDPu_time,SDPu_triangularization,SDPu_total_time,SDPu_robust
0,False,True,NaN,NaN,192,301,NaN,0.0,NaN,NaN,...,6x100,NaN,0.000000,NaN,trivially_solved,unknown,0.000000,NaN,6.090782,True
1,False,True,NaN,NaN,201,306,NaN,0.0,NaN,NaN,...,6x100,NaN,0.000000,NaN,trivially_solved,unknown,0.000000,NaN,1.732664,True
2,False,True,NaN,NaN,208,298,NaN,0.0,NaN,NaN,...,6x100,NaN,0.000000,NaN,trivially_solved,unknown,0.000000,NaN,1.720708,True
3,False,True,NaN,NaN,203,293,NaN,0.0,NaN,NaN,...,6x100,NaN,0.000000,NaN,trivially_solved,unknown,0.000000,NaN,1.723406,True
4,False,True,NaN,NaN,199,305,NaN,0.0,NaN,NaN,...,6x100,NaN,0.000000,NaN,trivially_solved,unknown,0.000000,NaN,1.908440,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,False,True,NaN,NaN,196,307,NaN,0.0,NaN,NaN,...,6x100,NaN,0.000000,NaN,trivially_solved,unknown,0.000000,NaN,1.701775,True
96,False,True,True,84229.0,149,191,True,1.0,True,True,...,6x100,-0.865488,251.804380,-0.842235,0,unknown,1102.682588,True,1104.400411,False
97,False,True,True,33280.0,192,283,True,1.0,True,True,...,6x100,-2.299313,164.277891,-2.276060,0,unknown,1037.783418,True,1039.636853,False
98,False,True,NaN,NaN,197,293,NaN,0.0,NaN,NaN,...,6x100,NaN,0.000000,NaN,trivially_solved,unknown,0.000000,NaN,1.754962,True
99,False,True,True,29400.0,202,287,True,1.0,True,True,...,6x100,-3.819140,153.741740,-3.795887,0,unknown,1005.150132,True,1006.898886,False

,start,end,verified_accuracy,total_examples,total_verified,total_falsified,timeout,mean_time,max_time,data_index
0,0,1,100.0,1,1,0,0,1.152255,1.152266,0
1,1,2,100.0,1,1,0,0,1.262294,1.262306,1
2,2,3,100.0,1,1,0,0,1.182590,1.182602,2
3,3,4,100.0,1,1,0,0,1.037226,1.037237,3
4,4,5,100.0,1,1,0,0,1.181951,1.181962,4
...,...,...,...,...,...,...,...,...,...,...
95,132,133,100.0,1,1,0,0,1.024921,1.024932,95
96,137,138,100.0,1,1,0,0,1.022767,1.022777,96
97,138,139,100.0,1,1,0,0,1.039625,1.039635,97
98,145,146,100.0,1,1,0,0,0.998874,0.998884,98
99,173,174,100.0,1,1,0,0,0.997601,0.997611,99

,start,end,verified_accuracy,total_examples,total_verified,total_falsified,timeout,mean_time,max_time,data_index
0,0,1,100.0,1,1,0,0,1.152255,1.152266,0
1,1,2,100.0,1,1,0,0,1.262294,1.262306,1
2,2,3,100.0,1,1,0,0,1.182590,1.182602,2
3,3,4,100.0,1,1,0,0,1.037226,1.037237,3
4,4,5,100.0,1,1,0,0,1.181951,1.181962,4
...,...,...,...,...,...,...,...,...,...,...
95,132,133,100.0,1,1,0,0,1.024921,1.024932,95
96,137,138,100.0,1,1,0,0,1.022767,1.022777,96
97,138,139,100.0,1,1,0,0,1.039625,1.039635,97
98,145,146,100.0,1,1,0,0,0.998874,0.998884,98
99,173,174,100.0,1,1,0,0,0.997601,0.997611,99

In [7]:
merged = list_of_tab.popitem()[1]
for name, tab in list_of_tab.items():
    print(f"Table: {name}")
    print(tab.head())
    print(tab.columns)


    merged = pd.merge(merged, tab, left_on="data_index", right_on="data_index")

Table: SDPu
   SDPu_LAST_LAYER  SDPu_MATRIX_BY_LAYERS SDPu_McC_betaz_logits  \
0            False                   True                   NaN
1            False                   True                   NaN
2            False                   True                   NaN
3            False                   True                   NaN
4            False                   True                   NaN

   SDPu_Nb_constraints  SDPu_Nb_stable_actives  SDPu_Nb_stable_inactives  \
0                  NaN                     192                       301
1                  NaN                     201                       306
2                  NaN                     208                       298
3                  NaN                     203                       293
4                  NaN                     199                       305

  SDPu_RLT  SDPu_RLT_prop SDPu_Tij SDPu_Tij_before_penultimate_layer  ...  \
0      NaN            0.0      NaN                               NaN  ...
1      NaN            0.0      NaN                               NaN  ...
2      NaN            0.0      NaN                               NaN  ...
3      NaN            0.0      NaN                               NaN  ...
4      NaN            0.0      NaN                               NaN  ...

   SDPu_network  SDPu_optimal_value SDPu_pretreatment_time  \
0         6x100                 NaN                    0.0
1         6x100                 NaN                    0.0
2         6x100                 NaN                    0.0
3         6x100                 NaN                    0.0
4         6x100                 NaN                    0.0

  SDPu_primal_obj_value       SDPu_status  SDPu_target SDPu_time  \
0                   NaN  trivially_solved      unknown       0.0
1                   NaN  trivially_solved      unknown       0.0
2                   NaN  trivially_solved      unknown       0.0
3                   NaN  trivially_solved      unknown       0.0
4                   NaN  trivially_solved      unknown       0.0

   SDPu_triangularization  SDPu_total_time  SDPu_robust
0                     NaN         6.090782         True
1                     NaN         1.732664         True
2                     NaN         1.720708         True
3                     NaN         1.723406         True
4                     NaN         1.908440         True

[5 rows x 33 columns]
Index(['SDPu_LAST_LAYER', 'SDPu_MATRIX_BY_LAYERS', 'SDPu_McC_betaz_logits',
       'SDPu_Nb_constraints', 'SDPu_Nb_stable_actives',
       'SDPu_Nb_stable_inactives', 'SDPu_RLT', 'SDPu_RLT_prop', 'SDPu_Tij',
       'SDPu_Tij_before_penultimate_layer', 'SDPu_USE_STABLE_ACTIVES',
       'SDPu_USE_STABLE_INACTIVES', 'SDPu_beta_logits_comparaison_1',
       'SDPu_beta_logits_comparaison_2', 'SDPu_bound_time', 'data_index',
       'SDPu_dataset', 'SDPu_dual_obj_value', 'SDPu_epsilon',
       'SDPu_iterations', 'SDPu_label', 'SDPu_label_predicted', 'SDPu_model',
       'SDPu_network', 'SDPu_optimal_value', 'SDPu_pretreatment_time',
       'SDPu_primal_obj_value', 'SDPu_status', 'SDPu_target', 'SDPu_time',
       'SDPu_triangularization', 'SDPu_total_time', 'SDPu_robust'],
      dtype='object')

In [8]:
merged.head()

,start,end,verified_accuracy,total_examples,total_verified,total_falsified,timeout,mean_time,max_time,data_index,...,SDPu_network,SDPu_optimal_value,SDPu_pretreatment_time,SDPu_primal_obj_value,SDPu_status,SDPu_target,SDPu_time,SDPu_triangularization,SDPu_total_time,SDPu_robust
0,0,1,100.0,1,1,0,0,1.152255,1.152266,0,...,6x100,NaN,0.0,NaN,trivially_solved,unknown,0.0,NaN,6.090782,True
1,1,2,100.0,1,1,0,0,1.262294,1.262306,1,...,6x100,NaN,0.0,NaN,trivially_solved,unknown,0.0,NaN,1.732664,True
2,2,3,100.0,1,1,0,0,1.182590,1.182602,2,...,6x100,NaN,0.0,NaN,trivially_solved,unknown,0.0,NaN,1.720708,True
3,3,4,100.0,1,1,0,0,1.037226,1.037237,3,...,6x100,NaN,0.0,NaN,trivially_solved,unknown,0.0,NaN,1.723406,True
4,4,5,100.0,1,1,0,0,1.181951,1.181962,4,...,6x100,NaN,0.0,NaN,trivially_solved,unknown,0.0,NaN,1.908440,True

In [ ]:
merged.columns

In [ ]:
list_of_tab["SDPu"]["data_index"]

In [9]:
merged[merged["SDPu_robust"] & merged["total_falsified"]]

,start,end,verified_accuracy,total_examples,total_verified,total_falsified,timeout,mean_time,max_time,data_index,...,SDPu_network,SDPu_optimal_value,SDPu_pretreatment_time,SDPu_primal_obj_value,SDPu_status,SDPu_target,SDPu_time,SDPu_triangularization,SDPu_total_time,SDPu_robust
33,33,34,0.0,1,0,1,0,0.645406,0.645412,33,...,6x100,NaN,0.0,NaN,trivially_solved,unknown,0.0,NaN,1.830944,True
62,62,63,0.0,1,0,1,0,0.615142,0.615148,62,...,6x100,NaN,0.0,NaN,trivially_solved,unknown,0.0,NaN,1.899453,True
72,73,74,0.0,1,0,1,0,0.392960,0.392964,72,...,6x100,NaN,0.0,NaN,trivially_solved,unknown,0.0,NaN,1.957681,True
88,97,98,0.0,1,0,1,0,0.466941,0.466946,88,...,6x100,NaN,0.0,NaN,trivially_solved,unknown,0.0,NaN,1.707413,True

In [ ]:
merged[merged["SDPu_1_label"] != merged["SDPu_1_label_predicted"]][["data_index", "SDPu_01_optimal_value", "SDPu_1_optimal_value", "SDPu_01_total_time", "SDPu_1_total_time", "SDPu_1_label", "SDPu_1_label_predicted"]]

In [ ]:
merged[~merged["SDPu_robust"] & merged["BB_total_verified"]]

In [ ]:
merged[~merged["SDPu_FP_RLT=100_robust"] & merged["Branch_and_Bound_beta_CROWN_total_falsified"]]